server:
  port: 8761
spring:
  profiles: dev
#    active: dev
  application:
    name: eurka-server
  security:
    user:
      name: xltc
      password: xltc
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:8762/eureka/

---
server:
  port: 8762
spring:
  profiles: pro
#    active: pro
  application:
    name: eurka-server
  security:
    user:
      name: xltc
      password: xltc
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:8761/eureka/
